FROM debian:jessie

RUN apt-get update --fix-missing
RUN apt-get install -y sudo xz-utils curl

RUN adduser --disabled-password --gecos '' docker
RUN adduser docker sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER docker
ENV USER docker
WORKDIR /home/docker

# https://nixos.wiki/wiki/Nix_Installation_Guide#Single-user_install
RUN sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
RUN curl https://nixos.org/nix/install | sh

RUN nix-shell --run echo "it works!"
