#!/usr/bin/env bash

set -euxo pipefail

box=${1:-sim2h_server}
branch=${2:-$( git rev-parse --abbrev-ref HEAD )}

docker build ./docker --build-arg DOCKER_BRANCH=$branch -f ./docker/Dockerfile.$box -t "holochain/holonix:$box.$branch" --no-cache
