ARG DOCKER_BRANCH=master
FROM holochain/holonix:minimal.${DOCKER_BRANCH} as build

ENV shellfile ./default.nix

RUN echo $NIX_PATH

RUN nix-env -i wget ps more killall gnugrep vim nano which
RUN nix-env -f $shellfile -iA holochain.trycp_server
RUN nix-collect-garbage

# https://stackoverflow.com/questions/22713551/how-to-flatten-a-docker-image#22714556
FROM scratch
COPY --from=build / /
WORKDIR /holonix

RUN mkdir /tmp/trycp/conductors -p

CMD trycp_server -p 9000 --port-range 5050-5070
