#!/usr/bin/env bash

set -euxo pipefail

box=${1:-sim2h_server}
branch=${2:-$( git rev-parse --abbrev-ref HEAD )}

docker run --rm -d -p 9000:9000/tcp -p 9000:9000/udp --name $box.$branch -t "holochain/holonix:$box.$branch"
