name: "update"

inputs:
  branch:
    description: ""
    required: true
  GITHUB_TOKEN:
    description: ""
    required: true
  HRA_GITHUB_TOKEN:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
      with:
        ref: ${{ inputs.branch }}
    - name: Install nix
      uses: cachix/install-nix-action@v16
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: holochain-ci
        signingKey: "${{ inputs.CACHIX_SIGNING_KEY }}"
        authToken: "${{ inputs.CACHIX_AUTH_TOKEN }}"
    - name: set up git config
      shell: bash
      run: |
        git config --global user.email "hrabot@holochain.org"
        git config --global user.name "Holochain Release Automation"
    - name: update holochain-nixpkgs
      shell: bash
      run: ./nix/update.sh holochain-nixpkgs
    - name: create pull request
      uses: peter-evans/create-pull-request@v3
      id: cpr1
      with:
        token: ${{ inputs.HRA_GITHUB_TOKEN }}
        title: update ${{ inputs.branch }}
        branch: auto-update/${{ inputs.branch }}
        labels: |
          release
        draft: false
        delete-branch: true
        reviewers: steveej
    - name: Enable Pull Request Automerge
      if: steps.cpr1.outputs.pull-request-operation == 'created' || steps.cpr1.outputs.pull-request-operation == 'updated'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ inputs.HRA_GITHUB_TOKEN}}
        pull-request-number: ${{ steps.cpr1.outputs.pull-request-number }}
        merge-method: squash
    - name: Auto approve Pull Request
      if: steps.cpr1.outputs.pull-request-operation == 'created' || steps.cpr1.outputs.pull-request-operation == 'updated'
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        number: ${{ steps.cpr1.outputs.pull-request-number }}
