name: "pr"
on:
  pull_request: {}

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          # - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install nix
        uses: cachix/install-nix-action@v18
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: holochain-ci
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Set NIX_PATH
        run: "echo NIX_PATH=nixpkgs=$(nix eval --impure --raw --expr '(import (import ./nix/sources.nix {}).holochain-nixpkgs {}).pkgs.path') >> $GITHUB_ENV"

      - name: hn-test
        run: |
          set -ex

          if [[ ${GITHUB_HEAD_REF} =~ auto-update/.*/scaffolding ]]; then
            include_arg="{ test = true; scaffolding = true; }"
          else
            include_arg="{ test = true; }"
          fi

          nix-shell --pure --keep NIX_PATH --arg include "${include_arg}"  --run '
              set -e
              hn-test
            '

  ci-jobs-succeed:
    needs: [tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check status
        env:
          RESULTS: "${{ toJSON(needs.*.result) }}"
        run: "[[ $(jq -n 'env.RESULTS | fromjson | unique == [\"success\"]') == \"true\" ]]\n"
