name: "pr"
on:
  pull_request: {}

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Set NIX_PATH
        run: "echo NIX_PATH=nixpkgs=$(nix eval --impure --raw --expr '(import (import ./nix/sources.nix {}).holochain-nixpkgs {}).pkgs.path') >> $GITHUB_ENV"

      - name: hn-test
        run: |
          set -ex

          if [[ ${GITHUB_HEAD_REF} =~ auto-update/.*/scaffolding ]]; then
            include_arg="{ test = true; scaffolding = true; }"
          else
            include_arg="{ test = true; }"
          fi

          nix-shell --pure --keep NIX_PATH --arg include "${include_arg}"  --run '
              set -e
              hn-test
            '

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ always() }}
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: steveeJ,jost-s,freesig,neonphog,thedavidmeister,maackle

  ci-jobs-succeed:
    needs: [tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check status
        env:
          RESULTS: "${{ toJSON(needs.*.result) }}"
        run: "[[ $(jq -n 'env.RESULTS | fromjson | unique == [\"success\"]') == \"true\" ]]\n"
