name: "auto-update"
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

concurrency:
  # group: ${{ github.head_ref }}
  group: ${{ inputs.branch }}
  cancel-in-progress: false
