name: "auto-update"
on:
  # push:
  #   branches:
  #     - pr-periodic-updates
  schedule:
    - cron: "0 6 * * *" # at 6 AM every day
  workflow_dispatch:
    inputs:
      only-base-ref:
        description: when this is set to 'true', updating of main and devleop branch will be skipped
        required: false
        default: "false"
        type: string
concurrency:
  # group: ${{ github.head_ref }}
  group: one
  cancel-in-progress: false

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main
          - develop
          - ${{ github.ref_name }}
        command:
          - name: update holochain-nixpkgs
            run: |
              ./nix/update.sh holochain-nixpkgs
    runs-on: "ubuntu-latest"
    if: ${{ inputs.only-base-ref == 'false' || github.ref_name == 'main' || github.ref_name == 'develop' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ matrix.branch }}
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: set up git config
        run: |
          git config --global user.email "hrabot@holochain.org"
          git config --global user.name "Holochain Release Automation"
      - name: ${{ matrix.command.name }}
        run: ${{ matrix.command.run }}
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        id: cpr1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN }}
          title: ${{ matrix.command.name }}
          branch: auto-update/${{ github.ref_name }}
          labels: |
            release
          draft: false
          delete-branch: true
          reviewers: steveej
      - name: Enable Pull Request Automerge
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN}}
          pull-request-number: ${{ steps.cpr1.outputs.pull-request-number }}
          merge-method: squash
      - name: Auto approve Pull Request
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr1.outputs.pull-request-number }}
  all-jobs-succeed:
    runs-on: "ubuntu-latest"
    needs: [update]
    steps: [{ name: "all-jobs-succeed", run: ":" }]
