name: "auto-update"
on:
  # push:
  #   branches:
  #     - pr/periodic-updates
  # schedule:
  #   - cron: "0 * * * 3" # at 6 AM every day
  workflow_dispatch: {}
concurrency:
  # group: ${{ github.head_ref }}
  group: one
  cancel-in-progress: false

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        command:
          - name: update holochain-nixpkgs
            run: |
              ./nix/update.sh holochain-nixpkgs
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: set up git config
        run: |
          git config --global user.email "hrabot@holochain.org"
          git config --global user.name "Holochain Release Automation"
      - name: ${{ matrix.command.name }}
        run: ${{ matrix.command.run }}
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        id: cpr1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN }}
          title: update holochain tags
          branch: auto-update/${{ github.ref_name }}
          labels: |
            release
          draft: false
          delete-branch: true
          reviewers: steveej
      - name: Enable Pull Request Automerge
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN}}
          pull-request-number: ${{ steps.cpr1.outputs.pull-request-number }}
          merge-method: squash
      - name: Auto approve Pull Request
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr1.outputs.pull-request-number }}
  all-jobs-succeed:
    runs-on: "ubuntu-latest"
    needs: [update]
    steps: [{ name: "all-jobs-succeed", run: ":" }]
