name: "update"

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      HRA_GITHUB_TOKEN:
        required: true

concurrency:
  group: ${{ github.evnts.inputs.branch }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.events.inputs.branch }}
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain-ci
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: set up git config
        run: |
          git config --global user.email "hrabot@holochain.org"
          git config --global user.name "Holochain Release Automation"
      - name: ${{ matrix.command.name }}
        run: ${{ matrix.command.run }}
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        id: cpr1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN }}
          title: ${{ matrix.command.name }}
          branch: auto-update/${{ inputs.branch }}
          labels: |
            release
          draft: false
          delete-branch: true
          reviewers: steveej
      - name: Enable Pull Request Automerge
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN}}
          pull-request-number: ${{ steps.cpr1.outputs.pull-request-number }}
          merge-method: squash
      - name: Auto approve Pull Request
        if: steps.cpr1.outputs.pull-request-operation != 'closed'
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr1.outputs.pull-request-number }}
